# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://aipsychphil.github.io/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title-short: "MP2"
title: "MP<sup>2</sup>: AI meets Moral Philosophy and Moral Psychology"

# Description of the Site
description: An Interdisciplinary Dialogue about Computational Ethics at NeurIPs 2023
# URL of Image of the Site

site-image: "/assets/images/An_expressionist_painting_of_a_number_of_academics_teaching_a_robot_the_difference_between_right_and_wrong.png"
# "/assets/images/robot_head.png"
# Keywords of the Site
site-keywords: philosophy, psychology, ai ethics, artificial intelligence
# URL for the Image of custom Favicon
favicon-url: "/assets/images/robot_head.png"

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: "/assets/images/An_expressionist_painting_of_a_number_of_academics_teaching_a_robot_the_difference_between_right_and_wrong.png"

submit: https://openreview.net/group?id=NeurIPS.cc/2023/Workshop/MP2

neurips: https://neurips.cc/virtual/2023/workshop/66528

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: aipsychphil@gmail.com
# facebook_username: thedevslot
# twitter_username: thedevslot
# instagram_username: thedevslot
# linkedin_username: thedevslot
# github_username:  thedevslot
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
# google-analytics: UA-163806439-1

# Disqus
# disqus-shortname: 

# Name of the Author
# author-name: 
# URL for the Image of the Author
# author-image: 
# 60 Words About the Author
# author-about: 
# author-url:

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
